### ISSUE TITLE
【Data/Server issue】502 Bad Gateway for the pretrained GNN vector data

### ISSUE THREAD

**Issue by Nikki0526** [zbc0315/synprepy#1]
Thank you for open-sourcing this nice work. Our team plan to do some follow-up work based on your pretrained GNN vector data. But I got something wrong with the pretrained GNN vector data at http://cimg.dcaiku.com/. When entering this webpage, the pretrained GNN vector data cannot be downloaded, with the server error "502 Bad Gateway, nginx/1.14.0 (Ubuntu)". I attached the figure of your website, could you please help me to check this problem? Thank you very much.
![website](https://github.com/zbc0315/synprepy/assets/42999257/80045412-c377-4da1-85df-555ed9ad5502)

**Comment by zbc0315** [comment]
Thank you for your reminder. The website's backend was unexpectedly interrupted and has now been restarted.

**Comment by Nikki0526** [comment]
Thank you very much for your help!
